// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB2_DT3TFrX5wCrMVXEzj32wxDF0vausmE',
    appId: '1:702430539556:web:9449422cc94ffb37648db1',
    messagingSenderId: '702430539556',
    projectId: 'chat-app-firebase-24740',
    authDomain: 'chat-app-firebase-24740.firebaseapp.com',
    storageBucket: 'chat-app-firebase-24740.appspot.com',
    measurementId: 'G-4M3MGR9N88',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD_lX3oHfDrtFwDgbywxIXP4UA2-AhPtEg',
    appId: '1:702430539556:android:efe00c74a5f57288648db1',
    messagingSenderId: '702430539556',
    projectId: 'chat-app-firebase-24740',
    storageBucket: 'chat-app-firebase-24740.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDZZwObR6UybcBIRZ3rTYNLqt4_EdeP7Bg',
    appId: '1:702430539556:ios:bd75874af09d987f648db1',
    messagingSenderId: '702430539556',
    projectId: 'chat-app-firebase-24740',
    storageBucket: 'chat-app-firebase-24740.appspot.com',
    iosClientId: '702430539556-nde27r8k39hac09qrt42qp6nck5q6r6s.apps.googleusercontent.com',
    iosBundleId: 'com.example.whatsappApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDZZwObR6UybcBIRZ3rTYNLqt4_EdeP7Bg',
    appId: '1:702430539556:ios:45661dd8bd43e615648db1',
    messagingSenderId: '702430539556',
    projectId: 'chat-app-firebase-24740',
    storageBucket: 'chat-app-firebase-24740.appspot.com',
    iosClientId: '702430539556-gr9urecu97qfccbn8beunb9c7kjperg1.apps.googleusercontent.com',
    iosBundleId: 'com.example.whatsappApp.RunnerTests',
  );
}
